In [65]:
import time
import pandas as pd
import requests
import urllib.parse as urlparse
import datetime
import urllib3
import math
from dateutil import parser as dtparser
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

In [2]:
start = "41.134073194962816,16.8184268094641"               # San Francisco
end = "41.131452672190235,16.827025971567991"                # Los Angeles
key = "SdbkkAPVV6GxzS7beuYj8mqYnSRWgUmx"                 # API Key

# Base URL
base_url = "https://api.tomtom.com/routing/1/calculateRoute/"

In [66]:
route_summaries = pd.DataFrame()

today = datetime.date.today()
print(today)
departure_time_start = datetime.datetime(today.year, today.month, today.day - 1, 0, 0, 0)
hour_range = range(0, 48)

for i in hour_range:

    minute, hour = math.modf(i / 2)
    # Calculate hours and minutes shift
    hours = round(hour)
    minutes = round(minute * 60)
    
    # Update an hour
    departure_time = departure_time_start.replace(hour=departure_time_start.hour + hours, minute=departure_time_start.minute + minutes)
    
    # Format datetime string
    departure_time = departure_time.strftime('%Y-%m-%dT%H:%M:%S')

    # Create request URL
    request_params = (
        urlparse.quote(start) + ":" + urlparse.quote(end) 
        # c_start + ":" + c_end 
        + "/json?departAt=" + urlparse.quote(departure_time)
        + "&sectionType=traffic&report=effectiveSettings&traffic=true&travelMode=car&computeTravelTimeFor=all"
    )
    request_url = base_url + request_params + "&key=" + key

    # Get data
    response = requests.get(request_url)

    # Convert to JSON
    json_result = response.json()

    # Get summary
    route_summary = json_result['routes'][0]['summary']

    # Collect data in DataFrame
    route_summaries = pd.concat([route_summaries, pd.json_normalize(route_summary)], ignore_index=True)
        
    print(f"Retrieving data: {i+1} / {len(hour_range)} >> {departure_time} ... ({response.status_code})")

    time.sleep(0.3)

2024-07-29
Retrieving data: 1 / 48 >> 2024-07-28T00:00:00 ... (200)
Retrieving data: 2 / 48 >> 2024-07-28T00:30:00 ... (200)
Retrieving data: 3 / 48 >> 2024-07-28T01:00:00 ... (200)
Retrieving data: 4 / 48 >> 2024-07-28T01:30:00 ... (200)
Retrieving data: 5 / 48 >> 2024-07-28T02:00:00 ... (200)
Retrieving data: 6 / 48 >> 2024-07-28T02:30:00 ... (200)
Retrieving data: 7 / 48 >> 2024-07-28T03:00:00 ... (200)
Retrieving data: 8 / 48 >> 2024-07-28T03:30:00 ... (200)
Retrieving data: 9 / 48 >> 2024-07-28T04:00:00 ... (200)
Retrieving data: 10 / 48 >> 2024-07-28T04:30:00 ... (200)
Retrieving data: 11 / 48 >> 2024-07-28T05:00:00 ... (200)
Retrieving data: 12 / 48 >> 2024-07-28T05:30:00 ... (200)
Retrieving data: 13 / 48 >> 2024-07-28T06:00:00 ... (200)
Retrieving data: 14 / 48 >> 2024-07-28T06:30:00 ... (200)
Retrieving data: 15 / 48 >> 2024-07-28T07:00:00 ... (200)
Retrieving data: 16 / 48 >> 2024-07-28T07:30:00 ... (200)
Retrieving data: 17 / 48 >> 2024-07-28T08:00:00 ... (200)
Retrieving data: 18 / 48 >> 2024-07-28T08:30:00 ... (200)
Retrieving data: 19 / 48 >> 2024-07-28T09:00:00 ... (200)
Retrieving data: 20 / 48 >> 2024-07-28T09:30:00 ... (200)
Retrieving data: 21 / 48 >> 2024-07-28T10:00:00 ... (200)
Retrieving data: 22 / 48 >> 2024-07-28T10:30:00 ... (200)
Retrieving data: 23 / 48 >> 2024-07-28T11:00:00 ... (200)
Retrieving data: 24 / 48 >> 2024-07-28T11:30:00 ... (200)
Retrieving data: 25 / 48 >> 2024-07-28T12:00:00 ... (200)
Retrieving data: 26 / 48 >> 2024-07-28T12:30:00 ... (200)
Retrieving data: 27 / 48 >> 2024-07-28T13:00:00 ... (200)
Retrieving data: 28 / 48 >> 2024-07-28T13:30:00 ... (200)
Retrieving data: 29 / 48 >> 2024-07-28T14:00:00 ... (200)
Retrieving data: 30 / 48 >> 2024-07-28T14:30:00 ... (200)
Retrieving data: 31 / 48 >> 2024-07-28T15:00:00 ... (200)
Retrieving data: 32 / 48 >> 2024-07-28T15:30:00 ... (200)
Retrieving data: 33 / 48 >> 2024-07-28T16:00:00 ... (200)
Retrieving data: 34 / 48 >> 2024-07-28T16:30:00 ... (200)
Retrieving data: 35 / 48 >> 2024-07-28T17:00:00 ... (200)
Retrieving data: 36 / 48 >> 2024-07-28T17:30:00 ... (200)
Retrieving data: 37 / 48 >> 2024-07-28T18:00:00 ... (200)
Retrieving data: 38 / 48 >> 2024-07-28T18:30:00 ... (200)
Retrieving data: 39 / 48 >> 2024-07-28T19:00:00 ... (200)
Retrieving data: 40 / 48 >> 2024-07-28T19:30:00 ... (200)
Retrieving data: 41 / 48 >> 2024-07-28T20:00:00 ... (200)
Retrieving data: 42 / 48 >> 2024-07-28T20:30:00 ... (200)
Retrieving data: 43 / 48 >> 2024-07-28T21:00:00 ... (200)
Retrieving data: 44 / 48 >> 2024-07-28T21:30:00 ... (200)
Retrieving data: 45 / 48 >> 2024-07-28T22:00:00 ... (200)
Retrieving data: 46 / 48 >> 2024-07-28T22:30:00 ... (200)
Retrieving data: 47 / 48 >> 2024-07-28T23:00:00 ... (200)
Retrieving data: 48 / 48 >> 2024-07-28T23:30:00 ... (200)

In [47]:
route_summaries

,lengthInMeters,travelTimeInSeconds,trafficDelayInSeconds,trafficLengthInMeters,departureTime,arrivalTime,noTrafficTravelTimeInSeconds,historicTrafficTravelTimeInSeconds,liveTrafficIncidentsTravelTimeInSeconds,time
0,778,60,0,0,2024-07-28T00:00:00+02:00,2024-07-28T00:00:59+02:00,60,60,60,2024-07-28T00:00:00
1,778,60,0,0,2024-07-28T00:30:00+02:00,2024-07-28T00:30:59+02:00,60,60,60,2024-07-28T00:30:00
2,778,60,0,0,2024-07-28T01:00:00+02:00,2024-07-28T01:00:59+02:00,60,60,60,2024-07-28T01:00:00
3,778,60,0,0,2024-07-28T01:30:00+02:00,2024-07-28T01:30:59+02:00,60,60,60,2024-07-28T01:30:00
4,778,60,0,0,2024-07-28T02:00:00+02:00,2024-07-28T02:00:59+02:00,60,60,60,2024-07-28T02:00:00
5,778,60,0,0,2024-07-28T02:30:00+02:00,2024-07-28T02:30:59+02:00,60,60,60,2024-07-28T02:30:00
6,778,60,0,0,2024-07-28T03:00:00+02:00,2024-07-28T03:00:59+02:00,60,60,60,2024-07-28T03:00:00
7,778,60,0,0,2024-07-28T03:30:00+02:00,2024-07-28T03:30:59+02:00,60,60,60,2024-07-28T03:30:00
8,778,60,0,0,2024-07-28T04:00:00+02:00,2024-07-28T04:01:00+02:00,60,60,60,2024-07-28T04:00:00
9,778,60,0,0,2024-07-28T04:30:00+02:00,2024-07-28T04:31:00+02:00,60,60,60,2024-07-28T04:30:00
10,778,60,0,0,2024-07-28T05:00:00+02:00,2024-07-28T05:01:00+02:00,60,60,60,2024-07-28T05:00:00
11,778,60,0,0,2024-07-28T05:30:00+02:00,2024-07-28T05:31:00+02:00,60,60,60,2024-07-28T05:30:00
12,778,61,0,0,2024-07-28T06:00:00+02:00,2024-07-28T06:01:00+02:00,60,61,61,2024-07-28T06:00:00
13,778,61,0,0,2024-07-28T06:30:00+02:00,2024-07-28T06:31:01+02:00,60,61,61,2024-07-28T06:30:00
14,778,63,0,0,2024-07-28T07:00:00+02:00,2024-07-28T07:01:03+02:00,60,63,63,2024-07-28T07:00:00
15,778,67,0,0,2024-07-28T07:30:00+02:00,2024-07-28T07:31:07+02:00,60,67,67,2024-07-28T07:30:00
16,778,73,0,0,2024-07-28T08:00:00+02:00,2024-07-28T08:01:12+02:00,60,73,73,2024-07-28T08:00:00
17,778,77,0,0,2024-07-28T08:30:00+02:00,2024-07-28T08:31:16+02:00,60,77,77,2024-07-28T08:30:00
18,778,79,0,0,2024-07-28T09:00:00+02:00,2024-07-28T09:01:18+02:00,60,79,79,2024-07-28T09:00:00
19,778,80,0,0,2024-07-28T09:30:00+02:00,2024-07-28T09:31:19+02:00,60,80,80,2024-07-28T09:30:00
20,778,81,0,0,2024-07-28T10:00:00+02:00,2024-07-28T10:01:20+02:00,60,81,81,2024-07-28T10:00:00
21,778,82,0,0,2024-07-28T10:30:00+02:00,2024-07-28T10:31:22+02:00,60,82,82,2024-07-28T10:30:00
22,778,84,0,0,2024-07-28T11:00:00+02:00,2024-07-28T11:01:23+02:00,60,84,84,2024-07-28T11:00:00
23,778,84,0,0,2024-07-28T11:30:00+02:00,2024-07-28T11:31:23+02:00,60,84,84,2024-07-28T11:30:00
24,778,83,0,0,2024-07-28T12:00:00+02:00,2024-07-28T12:01:23+02:00,60,83,83,2024-07-28T12:00:00
25,778,83,0,0,2024-07-28T12:30:00+02:00,2024-07-28T12:31:22+02:00,60,83,83,2024-07-28T12:30:00
26,778,80,0,0,2024-07-28T13:00:00+02:00,2024-07-28T13:01:19+02:00,60,80,80,2024-07-28T13:00:00
27,778,75,0,0,2024-07-28T13:30:00+02:00,2024-07-28T13:31:14+02:00,60,75,75,2024-07-28T13:30:00
28,778,71,0,0,2024-07-28T14:00:00+02:00,2024-07-28T14:01:11+02:00,60,71,71,2024-07-28T14:00:00
29,778,70,0,0,2024-07-28T14:30:00+02:00,2024-07-28T14:31:10+02:00,60,70,70,2024-07-28T14:30:00
30,778,72,0,0,2024-07-28T15:00:00+02:00,2024-07-28T15:01:11+02:00,60,72,72,2024-07-28T15:00:00
31,778,73,0,0,2024-07-28T15:30:00+02:00,2024-07-28T15:31:13+02:00,60,73,73,2024-07-28T15:30:00
32,778,77,0,0,2024-07-28T16:00:00+02:00,2024-07-28T16:01:16+02:00,60,77,77,2024-07-28T16:00:00
33,778,80,0,0,2024-07-28T16:30:00+02:00,2024-07-28T16:31:20+02:00,60,80,80,2024-07-28T16:30:00
34,778,85,0,0,2024-07-28T17:00:00+02:00,2024-07-28T17:01:24+02:00,60,85,85,2024-07-28T17:00:00
35,778,88,0,0,2024-07-28T17:30:00+02:00,2024-07-28T17:31:28+02:00,60,88,88,2024-07-28T17:30:00
36,778,90,0,0,2024-07-28T18:00:00+02:00,2024-07-28T18:01:30+02:00,60,90,90,2024-07-28T18:00:00
37,778,92,0,0,2024-07-28T18:30:00+02:00,2024-07-28T18:31:31+02:00,60,92,92,2024-07-28T18:30:00
38,778,91,0,0,2024-07-28T19:00:00+02:00,2024-07-28T19:01:31+02:00,60,91,91,2024-07-28T19:00:00
39,778,87,0,0,2024-07-28T19:30:00+02:00,2024-07-28T19:31:27+02:00,60,87,87,2024-07-28T19:30:00
40,778,81,0,0,2024-07-28T20:00:00+02:00,2024-07-28T20:01:21+02:00,60,81,81,2024-07-28T20:00:00
41,778,74,0,0,2024-07-28T20:30:00+02:00,2024-07-28T20:31:14+02:00,60,74,74,2024-07-28T20:30:00
42,778,68,0,0,2024-07-28T21:00:00+02:00,2024-07-28T21:01:08+02:00,60,68,68,2024-07-28T21:00:00
43,778,63,0,0,2024-07-28T21:30:00+02:00,2024-07-28T21:31:03+02:00,60,63,63,2024-07-28T21:30:00
44,778,60,0,0,2024-07-28T22:00:00+02:00,2024-07-28T22:00:59+02:00,60,60,60,2024-07-28T22:00:00
45,778,60,0,0,2024-07-28T22:30:00+02:00,2024-07-28T22:30:59+02:00,60,60,60,2024-07-28T22:30:00
46,778,60,0,0,2024-07-28T23:00:00+02:00,2024-07-28T23:00:59+02:00,60,60,60,2024-07-28T23:00:00
47,778,60,0,0,2024-07-28T23:30:00+02:00,2024-07-28T23:30:59+02:00,60,60,60,2024-07-28T23:30:00

In [59]:
route_analysis_df = pd.DataFrame()

for index, summary in route_summaries.iterrows():
    # Get length of road
    length_in_meters = summary['lengthInMeters']
    # Calculate free flow speed in km/h
    free_flow_speed = length_in_meters / summary['noTrafficTravelTimeInSeconds']  * 3.6
    # Calculate traffic speed in km/h
    traffic_speed = length_in_meters / summary['travelTimeInSeconds']  * 3.6
    # Calculate traffic density
    density_factor = free_flow_speed / traffic_speed
    avg_vehicle_length = 4.6
    
    # https://www.amsi.org.au/teacher_modules/pdfs/Maths_delivers/Braking5.pdf
    breaking_distance = (traffic_speed ** 2) / 20 # b = m/s 
    
    # The number of vehicles is calculated as the traffic density * length of road divided by the average length of vehicles and recommended breaking distance
    vehicles = round(density_factor * length_in_meters / avg_vehicle_length)

    # Departure time
    datetime = summary['departureTime']
    
    results = {"datetime": datetime, "free_flow_speed": free_flow_speed, "traffic_speed": traffic_speed, "density_factor": density_factor, "number_of_vehicles": vehicles }
    
    # Convert to data frame and append
    route_analysis_df = pd.concat([route_analysis_df, pd.json_normalize(results)], ignore_index=True)

dt = dtparser.parse(route_analysis_df.at[0, 'datetime'])
route_analysis_df.to_csv(f'{dt.year}-{dt.month:02d}-{dt.day:02d}.csv', index=False)

In [49]:
route_analysis_df

,time,free_flow_speed,traffic_speed,density_factor,number_of_vehicles
0,2024-07-28T00:00:00+02:00,46.68,46.680000,1.000000,169
1,2024-07-28T00:30:00+02:00,46.68,46.680000,1.000000,169
2,2024-07-28T01:00:00+02:00,46.68,46.680000,1.000000,169
3,2024-07-28T01:30:00+02:00,46.68,46.680000,1.000000,169
4,2024-07-28T02:00:00+02:00,46.68,46.680000,1.000000,169
5,2024-07-28T02:30:00+02:00,46.68,46.680000,1.000000,169
6,2024-07-28T03:00:00+02:00,46.68,46.680000,1.000000,169
7,2024-07-28T03:30:00+02:00,46.68,46.680000,1.000000,169
8,2024-07-28T04:00:00+02:00,46.68,46.680000,1.000000,169
9,2024-07-28T04:30:00+02:00,46.68,46.680000,1.000000,169
10,2024-07-28T05:00:00+02:00,46.68,46.680000,1.000000,169
11,2024-07-28T05:30:00+02:00,46.68,46.680000,1.000000,169
12,2024-07-28T06:00:00+02:00,46.68,45.914754,1.016667,172
13,2024-07-28T06:30:00+02:00,46.68,45.914754,1.016667,172
14,2024-07-28T07:00:00+02:00,46.68,44.457143,1.050000,178
15,2024-07-28T07:30:00+02:00,46.68,41.802985,1.116667,189
16,2024-07-28T08:00:00+02:00,46.68,38.367123,1.216667,206
17,2024-07-28T08:30:00+02:00,46.68,36.374026,1.283333,217
18,2024-07-28T09:00:00+02:00,46.68,35.453165,1.316667,223
19,2024-07-28T09:30:00+02:00,46.68,35.010000,1.333333,226
20,2024-07-28T10:00:00+02:00,46.68,34.577778,1.350000,228
21,2024-07-28T10:30:00+02:00,46.68,34.156098,1.366667,231
22,2024-07-28T11:00:00+02:00,46.68,33.342857,1.400000,237
23,2024-07-28T11:30:00+02:00,46.68,33.342857,1.400000,237
24,2024-07-28T12:00:00+02:00,46.68,33.744578,1.383333,234
25,2024-07-28T12:30:00+02:00,46.68,33.744578,1.383333,234
26,2024-07-28T13:00:00+02:00,46.68,35.010000,1.333333,226
27,2024-07-28T13:30:00+02:00,46.68,37.344000,1.250000,211
28,2024-07-28T14:00:00+02:00,46.68,39.447887,1.183333,200
29,2024-07-28T14:30:00+02:00,46.68,40.011429,1.166667,197
30,2024-07-28T15:00:00+02:00,46.68,38.900000,1.200000,203
31,2024-07-28T15:30:00+02:00,46.68,38.367123,1.216667,206
32,2024-07-28T16:00:00+02:00,46.68,36.374026,1.283333,217
33,2024-07-28T16:30:00+02:00,46.68,35.010000,1.333333,226
34,2024-07-28T17:00:00+02:00,46.68,32.950588,1.416667,240
35,2024-07-28T17:30:00+02:00,46.68,31.827273,1.466667,248
36,2024-07-28T18:00:00+02:00,46.68,31.120000,1.500000,254
37,2024-07-28T18:30:00+02:00,46.68,30.443478,1.533333,259
38,2024-07-28T19:00:00+02:00,46.68,30.778022,1.516667,257
39,2024-07-28T19:30:00+02:00,46.68,32.193103,1.450000,245
40,2024-07-28T20:00:00+02:00,46.68,34.577778,1.350000,228
41,2024-07-28T20:30:00+02:00,46.68,37.848649,1.233333,209
42,2024-07-28T21:00:00+02:00,46.68,41.188235,1.133333,192
43,2024-07-28T21:30:00+02:00,46.68,44.457143,1.050000,178
44,2024-07-28T22:00:00+02:00,46.68,46.680000,1.000000,169
45,2024-07-28T22:30:00+02:00,46.68,46.680000,1.000000,169
46,2024-07-28T23:00:00+02:00,46.68,46.680000,1.000000,169
47,2024-07-28T23:30:00+02:00,46.68,46.680000,1.000000,169